services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: isamoda_db
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./Backend
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "${PORT:-3200}:3200"
    env_file:
      - ./Backend/src/config/.env
    environment:
      DB_URL: "postgresql://postgres:mysecretpassword@database:${POSTGRES_PORT:-5432}/isamoda_db"

  frontend:
    build: ./Frontend
    ports:
      - "5173:80"  
    env_file:
      - ./Frontend/.env
    depends_on:
      - backend
