version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "${PORT}:${PORT}" # Usa la variable PORT definida en el archivo .env del backend
    env_file:
      - ./backend/src/config/.env # Carga las variables desde el archivo .env

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:80" # Usa el puerto definido en el archivo .env del frontend
    env_file:
      - ./frontend/.env # Carga las variables desde el archivo .env
    depends_on:
      - backend
