version: '3.8'

networks:
  app-network:

services:
  database:
    image: postgres:13
    env_file:
      - ./Backend/src/config/.env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backend:
    build: ./Backend
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "${PORT:-3200}:3200"
    env_file:
      - ./Backend/src/config/.env
    networks:
      - app-network

  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

